### ISSUE TITLE
FoundError:   conda activate tf_24; python test_trajectories.py --settings_file=config/test_settings.yaml

### ISSUE THREAD

**Issue by linzgood** [uzh-rpg/agile_autonomy#30]
` conda activate tf_24`
CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?

ThinkPad-P15v-Gen-1:  `conda info --envs`

conda environments:
tf_24                    /home/linzgood/anaconda3/envs/tf_24
root                  *  /home/linzgood/anaconda3

ThinkPad-P15v-Gen-1:  `source activate`
ThinkPad-P15v-Gen-1:  `source deactivate`
But the error still remain，anybody  met the same error？Thanks

**Comment by linzgood** [comment]
```
cd ～/agile_autonomy_ws/catkin_aa/src/agile_autonomy/planner_learning
source ～/agile_autonomy_ws/catkin_aa/devel/setup.bash
python test_trajectories.py --settings_file=config/test_settings.yaml
```

FoundError: 
Traceback (most recent call last):
  File "test_trajectories.py", line 4, in <module>
    from dagger_training import Trainer
  File "/home/linzgood/agile_autonomy_ws/catkin_aa/src/agile_autonomy/planner_learning/dagger_training.py", line 10, in <module>
    from PlannerLearning import PlannerLearning
  File "/home/linzgood/agile_autonomy_ws/catkin_aa/src/agile_autonomy/planner_learning/src/PlannerLearning/PlannerLearning.py", line 4, in <module>
    import open3d as o3d
  File "/home/linzgood/anaconda3/lib/python3.6/site-packages/open3d/__init__.py", line 56, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/home/linzgood/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/linzgood/anaconda3/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/linzgood/anaconda3/lib/python3.6/site-packages/open3d/cpu/pybind.cpython-36m-x86_64-linux-gnu.so)
