### ISSUE TITLE
python test_trajectories.py --settings_file=config/test_settings.yaml

### ISSUE THREAD

**Issue by slyangxu** [uzh-rpg/agile_autonomy#69]
Traceback (most recent call last):
  File "test_trajectories.py", line 4, in <module>
    from dagger_training import Trainer
  File "/home/zjx/agile_autonomy_ws/catkin_aa/src/agile_autonomy/planner_learning/dagger_training.py", line 10, in <module>
    from PlannerLearning import PlannerLearning
  File "/home/zjx/agile_autonomy_ws/catkin_aa/src/agile_autonomy/planner_learning/src/PlannerLearning/PlannerLearning.py", line 4, in <module>
    import open3d as o3d
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/open3d/__init__.py", line 102, in <module>
    import open3d.visualization
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/open3d/visualization/__init__.py", line 38, in <module>
    from .draw_plotly import draw_plotly
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/open3d/visualization/draw_plotly.py", line 31, in <module>
    from dash import html
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/dash/__init__.py", line 5, in <module>
    from .dependencies import (  # noqa: F401,E402
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/dash/dependencies.py", line 4, in <module>
    from ._validate import validate_callback
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/dash/_validate.py", line 5, in <module>
    import flask
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/flask/globals.py", line 57, in <module>
    _cv_app, unbound_message=_no_app_msg
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

**Comment by slyangxu** [comment]
>



> Traceback (most recent call last): File "test_trajectories.py", line 4, in from dagger_training import Trainer File "/home/zjx/agile_autonomy_ws/catkin_aa/src/agile_autonomy/planner_learning/dagger_training.py", line 10, in from PlannerLearning import PlannerLearning File "/home/zjx/agile_autonomy_ws/catkin_aa/src/agile_autonomy/planner_learning/src/PlannerLearning/PlannerLearning.py", line 4, in import open3d as o3d File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/open3d/**init**.py", line 102, in import open3d.visualization File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/open3d/visualization/**init**.py", line 38, in from .draw_plotly import draw_plotly File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/open3d/visualization/draw_plotly.py", line 31, in from dash import html File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/dash/**init**.py", line 5, in from .dependencies import ( # noqa: F401,E402 File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/dash/dependencies.py", line 4, in from ._validate import validate_callback File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/dash/_validate.py", line 5, in import flask File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/flask/**init**.py", line 4, in from . import json as json File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/flask/json/**init**.py", line 8, in from ..globals import current_app File "/home/zjx/anaconda3/envs/tf_24/lib/python3.7/site-packages/flask/globals.py", line 57, in _cv_app, unbound_message=_no_app_msg TypeError: **init**() got an unexpected keyword argument 'unbound_message'

Hi, after installing the simulation environment and other preparations, I get an error when I open the second terminal to run this command 'python test_trajectories.py --settings_file=config/test_settings.yaml', how can I solve it? Thanks.

**Comment by slyangxu** [comment]
Hi, after installing the simulation environment and other preparations, I get an error when I open the second terminal to run this command 'python test_trajectories.py --settings_file=config/test_settings.yaml', how can I solve it? Thanks.
